repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
      - id: mypy
